Roi msgs
ros4hri/pyhri pull request #6
Opened 2023-03-23 16:29 UTC by Luca-Pozzi

# Use `sensor_msgs/RegionOfInterest` for ROI (fixes #5)
Solves [this issue](https://github.com/ros4hri/pyhri/issues/5) related to `pyhri` apparently being the only package in the ROS4HRI framework using `hri_msgs/NormalizedRegionOfInterest2D` instead of `sensor_msgs/RegionOfInterest`.

With respect to simply undoing commit https://github.com/ros4hri/pyhri/commit/be95f6a9ed7caf397f532a3d713496451047266e, in `face.py` it also switches from `hri_msgs/NormalizedPointOfInterest2D` to `sensor_msgs/RegionOfInterest` to represent face ROI. 

# Solve `AttributeError` on first detection
Due to `_hrilistener = None` in `__init__` of `person.py`, at the first call to one of the `on_<x>_id` callbacks, the following error was thrown:
```
[ERROR] [1679581959.014495]: bad callback: <bound method Person.on_face_id of <hri.person.Person object at 0x7f1f2f63b520>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/luca/hri_ws/src/pyhri/src/hri/person.py", line 138, in on_face_id
    if msg.data and msg.data in self._hrilistener._faces:
AttributeError: 'NoneType' object has no attribute '_faces'
```
due to the `_hrilistener` attribute being not set by `hri.py` yet. The error do not cause any major issues, as everything work just smoothly from the second detection on.
It has been fixed by adding a `and self._hrilistener is not None` check in each `on_<x>_id` callbacks.

2023-03-27 15:55 UTC, severin-lemaignan requested changes
thanks for the PR! much appreciated! 3 minor fixes, and then, happy to merge!

2023-03-27 15:55 UTC, severin-lemaignan commented on src/hri/person.py
> +        if msg.data and self._hrilistener is not None and msg.data in self._hrilistener._faces:
`self.hrilistener` is sufficient, no need for `is not None`

2023-03-27 15:55 UTC, severin-lemaignan commented on src/hri/person.py
> +        if msg.data and self._hrilistener is not None and msg.data in self._hrilistener._bodies:
same

2023-03-27 15:55 UTC, severin-lemaignan commented on src/hri/person.py
> +        if msg.data and self._hrilistener is not None and msg.data in self._hrilistener._voices:
same

2023-03-28 07:25 UTC, Luca-Pozzi commented on src/hri/person.py
> +        if msg.data and self._hrilistener is not None and msg.data in self._hrilistener._faces:
Good point, done!

2023-03-28 11:48 UTC, severin-lemaignan commented
Thanks! can you squash commits 16ccf9c3816d0c895b94f534fb71def4c562f965 and be03f62dd5c139d29e457aad0198e3cbf5cc2278 before I merge, please?

2023-04-04 15:25 UTC, Luca-Pozzi commented
Hi @severin-lemaignan!
Sorry for bothering, I squashed the commits (correctly, I hope) last week. Is there anything else I should do?

2023-04-12 13:18 UTC, merged

2023-04-12 13:18 UTC, severin-lemaignan commented
thanks! merged!

2023-04-12 13:30 UTC, severin-lemaignan commented
I've released `pyhri-0.4.0` with those changes, that should be soon merged in noetic: https://github.com/ros/rosdistro/pull/36812